- name: install the yum repository
  sudo: yes
  get_url: url=http://everdene.iplantcollaborative.org/rpms/iplant-release.repo dest=/etc/yum.repos.d/iplant-release.repo

# - name: Install supervisord
#   pip: name=supervisor version=3.1.3
#   notify:
#     - restart supervisord
#   tags:
#     - supervisord-setup
#     - supervisord-install
#     - supervisord

- name: Copy the supervisord init script into place
  sudo: yes
  sudo_user: root
  copy: src=remote_files/supervisord/supervisord dest=/etc/init.d/supervisord owner=root group=root mode=0755 force=yes
  notify:
    - restart supervisord
  tags:
    - supervisord-setup
    - supervisord-install-init
    - supervisord

- name: Create the /etc/iplant/de/supervisord/ directory
  file: path=/etc/iplant/de/supervisord owner=iplant group=iplant state=directory
  notify:
    - restart supervisord
  tags:
    - supervisord-setup
    - supervisord-create-conf-dir
    - supervisord

- name: Place the /etc/supervisor.conf directory
  copy: src=remote_files/supervisord/supervisord.conf dest=/etc/supervisord.conf owner=root group=root mode=0644
  notify:
    - restart supervisord
  tags:
    - supervisord-setup
    - supervisor-copy-conf
    - supervisord
