- name: install epel-release for vmtools
  yum: name=epel-release state=present
  when: ansible_distribution == 'CentOS'

- name: install open-vm-tools from epel
  yum: 
     name=open-vm-tools state=present
  when: ansible_distribution == 'CentOS'

- name: restart machine
  debug: msg="VM Tools playbook completed. Please check output and reboot if necessary."
