- name: install epel-release for vmtools
  yum: name=epel-release state=present
  when: ansible_distribution == 'CentOS'

- name: install open-vm-tools from epel
  yum: 
     name=open-vm-tools state=present
  when: ansible_distribution == 'CentOS'

- name: restart machine
  command: shutdown -r now "rebooting to install open-vm-tools"
  async: 0
  poll: 0
  ignore_errors: true

- name: Wait for Server to Restart
  local_action:
    wait_for
    host={{ inventory_hostname }}
    port=22
    delay=15
    timeout=300
  sudo: false

