---

- name: ensure EPEL repository for RedHat7/CentOS7
  yum: name=epel-release state=latest
  when: ansible_os_family == "RedHat" and
        ansible_distribution_major_version == "7"
  tags: dataverse

- name: install java-1.7.0-openjdk-devel. dataverse currently requires this version.
  yum: name="{{item}}" state=latest
  with_items:
    - httpd
    - java-1.7.0-openjdk-devel
    - jq
    - mod_ssl
    - perl
  when: ansible_os_family == "RedHat" and
        ansible_distribution_major_version == "7"
  tags: dataverse

- name: install shibboleth repo
  get_url: url=http://download.opensuse.org/repositories/security:/shibboleth/CentOS_7/security:shibboleth.repo dest=/etc/yum.repos.d owner=root group=root mode=0644
  when: ansible_os_family == "RedHat" and
        ansible_distribution_major_version == "7"
  tags: dataverse

- name: install shibboleth rpms
  yum: name="{{item}}" state=latest
  with_items:
    - shibboleth
    - shibboleth-embedded-ds
  when: ansible_os_family == "RedHat" and
        ansible_distribution_major_version == "7"
  tags: dataverse

# TODO: fix this.
- name: configure apache/shib to front glassfish
  debug: msg="Apache and Shibboleth packages installed. Please see http://guides.dataverse.org/en/latest/installation/shibboleth.html for detailed configuration instructions."

- name: download glassfish4. unarchive urls supported in ansible 2.0
  get_url: url=http://dlc-cdn.sun.com/glassfish/4.1/release/glassfish-4.1.zip dest=/tmp mode=0644
  tags: dataverse

- name: unzip glassfish.
  shell: unzip /tmp/glassfish-4.1.zip -d /usr/local
  tags: dataverse

- name: create glassfish service group
  group: name={{ dataverse_gf_group }} state=present
  tags: dataverse

- name: create glassfish service account
  user: name={{ dataverse_gf_user }} group={{ dataverse_gf_group }}
  tags: dataverse

- name: glassfish runs as service account, should own files/
  file: path={{ dataverse_filesdir }} owner={{ dataverse_gf_user }} group={{ dataverse_gf_group }} state=directory
  tags: dataverse

- name: glassfish runs as service account, should own itself, for now.
  file: path=/usr/local/glassfish4 owner={{ dataverse_gf_user }} group={{ dataverse_gf_group }} state=directory recurse=yes
  tags: dataverse

- name: remove old weld jar
  shell: /bin/rm /usr/local/glassfish4/glassfish/modules/weld-osgi-bundle.jar
  tags: dataverse

- name: get patched weld jar
  get_url: url=http://central.maven.org/maven2/org/jboss/weld/weld-osgi-bundle/2.2.10.SP1/weld-osgi-bundle-2.2.10.SP1-glassfish4.jar 
        dest=/usr/local/glassfish4/glassfish/modules owner={{ dataverse_gf_user }} group={{ dataverse_gf_group }} mode=0644
  tags: dataverse

- name: install glassfish systemd conf file
  template: src=glassfish.service.j2 dest=/usr/lib/systemd/system/glassfish.service owner=root group=root mode=0644
  when: ansible_os_family == "RedHat" and
        ansible_distribution_major_version == "7"
  tags: dataverse

- name: reload systemd because systemd
  shell: systemctl daemon-reload
  when: ansible_os_family == "RedHat" and
        ansible_distribution_major_version == "7"
  tags: dataverse

- name: start and enable glassfish
  service: name=glassfish enabled=yes state=started
  tags: dataverse

- name: install postgres-9.3 repo. dataverse doesn't yet like 9.4 OotB.
  yum: name=http://yum.postgresql.org/9.3/redhat/rhel-7-x86_64/pgdg-centos93-9.3-2.noarch.rpm state=present
  when: ansible_os_family == "RedHat" and
        ansible_distribution_major_version == "7"
  tags: dataverse

- name: install postgres-9.3
  yum: name=postgresql93-server state=latest
  tags: dataverse

- name: init postgres-9.3
  shell: /usr/pgsql-9.3/bin/postgresql93-setup initdb
  tags: dataverse

- name: install pg_hba.conf
  copy: src=pg_hba.conf dest=/var/lib/pgsql/9.3/data owner=postgres group=postgres mode=0644
  tags: dataverse

- name: enable postgres-9.3 on boot
  service: name=postgresql-9.3 enabled=yes
  tags: dataverse

- name: start postgres-9.3
  service: name=postgresql-9.3 state=started
  tags: dataverse

- name: download solr. unarchive urls supported in 2.0.
  get_url: url=https://archive.apache.org/dist/lucene/solr/4.6.0/solr-4.6.0.tgz dest=/tmp mode=0644
  tags: dataverse

- name: unpack solr
  shell: tar xvfz /tmp/solr-4.6.0.tgz -C /usr/local
  tags: dataverse

- name: drop solr version
  command: mv /usr/local/solr-4.6.0 /usr/local/solr
  tags: dataverse

- name: get updated solr schema
  get_url: url=https://github.com/IQSS/dataverse/releases/download/v4.2.1/schema.xml dest=/usr/local/solr/example/solr/collection1/conf/ owner={{ dataverse_gf_user }} group={{ dataverse_gf_group }} mode=0644
  tags: dataverse

- name: install solr systemd conf file
  copy: src=solr.service dest=/usr/lib/systemd/system owner=root group=root mode=0644
  when: ansible_os_family == "RedHat" and
        ansible_distribution_major_version == "7"
  tags: dataverse

- name: reload systemd because systemd
  shell: systemctl daemon-reload
  when: ansible_os_family == "RedHat" and
        ansible_distribution_major_version == "7"
  tags: dataverse

- name: enable solr on boot, start solr
  service: name=solr enabled=yes state=started
  tags: dataverse
