---

- name: dataverse: pull dvinstall.zip
  get_url: url=https://github.com/IQSS/dataverse/releases/download/v4.2.1/dvinstall-4.2.1.zip dest=/tmp mode=0644
  tags: dataverse

- name: dataverse: unzip dvinstall.zip
  shell: unzip /tmp/dvinstall-4.2.1.zip
  tags: dataverse

- name: dataverse: copy config template
  template: src=install.de.j2 dest=/tmp/dvinstall/install.de owner=root group=root mode=0755
  tags: dataverse

- name: dataverse: install!
  shell: /tmp/dvinstall/install.de
  tags: dataverse

- name: dataverse: copy admin password hash (set group_var as SHA256)
  template: src=adminpass.txt.j2 dest=/tmp/dvinstall/adminpass.txt owner=root group=root mode=0600
  tags: dataverse

- name: dataverse: set admin password
  shell: /usr/local/glassfish4/glassfish/bin/asadmin --passwordfile /tmp/dvinstall/adminpass.txt change-admin-password
  tags: dataverse

- name: dataverse: enable secure admin
  shell: /usr/local/glassfish4/glassfish/bin/asadmin --passwordfile /tmp/dvinstall/adminpass.txt enable-secure-admin
  tags: dataverse
