---

- name: ensure EPEL repository for RedHat7/CentOS7
  yum: name=epel-release state=latest
  when: ansible_os_family == "RedHat" and
        ansible_distribution_major_version == "7"
  tags: dataverse

- name: install java-1.7.0-openjdk-devel for RedHat/CentOS. Dataverse currently requires this version.
  yum: name="{{item}}" state=latest
  with_items:
    - git
    - httpd
    - java-1.7.0-openjdk-devel
    - jq
    - mod_ssl
    - perl
    - python-psycopg2
  when: ansible_os_family == "RedHat" and
        ansible_distribution_major_version == "7"
  tags: dataverse

- name: install openjdk-7-jdk, apache, etc. for Ubuntu/Debian.
  apt: name="{{item}}" state=latest update_cache=true
  with_items:
    - apache2
    - git
    - jq
    - libapache2-mod-shib2
    - openjdk-7-jdk
    - perl5
    - python-psycopg2
  when: ansible_os_family == "Debian"
  tags: dataverse

- name: install shibboleth repo for RedHat/CentOS7
  get_url: url=http://download.opensuse.org/repositories/security:/shibboleth/CentOS_7/security:shibboleth.repo dest=/etc/yum.repos.d owner=root group=root mode=0644
  when: ansible_os_family == "RedHat" and
        ansible_distribution_major_version == "7"
  tags: dataverse

- name: install Shibboleth RPMs for RedHat/CentOS7
  yum: name="{{item}}" state=latest
  with_items:
    - shibboleth
    - shibboleth-embedded-ds
  when: ansible_os_family == "RedHat" and
        ansible_distribution_major_version == "7"
  tags: dataverse

# TODO: install shib on Debian/Ubuntu

- name: install http redirect template
  template: src=http.redirect.conf.j2 dest=/etc/httpd/conf.d/http.redirect.conf owner=root group=root mode=0644
  when: ansible_os_family == "RedHat" and
        ansible_distribution_major_version == "7"
  tags: dataverse

- name: install mod_ssl template
  template: src=ssl.conf.j2 dest=/etc/httpd/conf.d/ssl.conf owner=root group=root mode=0644
  when: ansible_os_family == "RedHat" and
        ansible_distribution_major_version == "7"
  tags: dataverse

- name: install shibboleth2.xml template
  template: src=shibboleth2.xml.j2 dest=/etc/shibboleth/ owner=root group=root mode=0644
  tags: dataverse

- name: copy attribute-map.xml file
  copy: src=attribute-map.xml dest=/etc/shibboleth/ owner=root group=root mode=0644
  tags: dataverse

- name: copy TestShib IdP metadata XML file
  copy: src=dataverse-idp-metadata.xml dest=/etc/shibboleth/ owner=root group=root mode=0644
  tags: dataverse

- name: enable and start shibd on RedHat / CentOS 7.
  service: name=shibd enabled=yes state=started
  when: ansible_os_family == "RedHat" and
        ansible_distribution_major_version == "7"
  tags: dataverse

- name: enable and start httpd on RedHat / CentOS 7.
  service: name=httpd enabled=yes state=started
  when: ansible_os_family == "RedHat" and
        ansible_distribution_major_version == "7"
  tags: dataverse

# TODO: restart shib on Debian/Ubuntu

- name: restart apache2 on Debian/Ubuntu
  service: name=apache2 state=restarted
  when: ansible_os_family == "Debian"
  tags: dataverse

- name: install postgres-9.3 repo on Redhat / CentOS 7.
  yum: name=http://yum.postgresql.org/9.3/redhat/rhel-7-x86_64/pgdg-centos93-9.3-2.noarch.rpm state=present
  when: ansible_os_family == "RedHat" and
        ansible_distribution_major_version == "7"
  tags: dataverse

- name: install postgres-9.3 on RedHat / CentOS 7.
  yum: name=postgresql93-server state=latest
  when: ansible_os_family == "RedHat" and
        ansible_distribution_major_version == "7"
  tags: dataverse

- name: init postgres-9.3 on RedHat / CentOS 7.
  shell: /usr/pgsql-9.3/bin/postgresql93-setup initdb
  when: ansible_os_family == "RedHat" and
        ansible_distribution_major_version == "7"
  tags: dataverse

- name: install and init postgres-9.3 for Debian/Ubuntu
  apt: pkg=postgresql-9.3 state=latest update_cache=true
  when: ansible_os_family == "Debian"
  tags: dataverse

- name: install pg_hba.conf on RedHat / CentOS 7.
  copy: src=pg_hba.conf dest=/var/lib/pgsql/9.3/data owner=postgres group=postgres mode=0644
  when: ansible_os_family == "RedHat" and
        ansible_distribution_major_version == "7"
  tags: dataverse

- name: enable postgres-9.3 on RedHat / CentOS 7.
  service: name=postgresql-9.3 enabled=yes
  when: ansible_os_family == "RedHat" and
        ansible_distribution_major_version == "7"
  tags: dataverse

- name: start postgres-9.3 on RedHat / CentOS 7.
  service: name=postgresql-9.3 state=started
  when: ansible_os_family == "RedHat" and
        ansible_distribution_major_version == "7"
  tags: dataverse

- name: install pg_hba.conf on Debian/Ubuntu
  copy: src=pg_hba.conf dest=/etc/postgresql/9.3/main owner=postgres group=postgres mode=0644
  when: ansible_os_family == "Debian"
  tags: dataverse

- name: restart postgres on Debian/Ubuntu
  service: postgresql state=restarted
  when: ansible_os_family == "Debian"
  tags: dataverse

- name: create glassfish postgres database
  postgresql_db: name={{ dataverse_db }}
  tags: dataverse

- name: create glassfish postgres user, set permissions
  postgresql_user: db={{ dataverse_db }} name={{ dataverse_dbuser }} password={{ dataverse_dbpass }} role_attr_flags=NOSUPERUSER,CREATEDB,CREATEROLE,INHERIT,LOGIN
  tags: dataverse

- name: download glassfish4. unarchive urls supported in ansible 2.0
  get_url: url=http://dlc-cdn.sun.com/glassfish/4.1/release/glassfish-4.1.zip dest=/tmp mode=0644
  tags: dataverse

- name: unzip glassfish. unarchive urls supported in ansible 2.0
  shell: unzip /tmp/glassfish-4.1.zip -d /tmp
  tags: dataverse

- name: ensure dataverse_gf_root exists
  file: path={{ dataverse_gf_root }} state=directory owner=root group=root mode=0755
  tags: dataverse

- name: copy glassfish into desired glassfish root. (synchronize module barfs even without pty, file wants to copy local/remote. shell it is.)
  shell: "/bin/cp -r /tmp/glassfish4/* {{ dataverse_gf_root }}"
  tags: dataverse

- name: create glassfish service group
  group: name={{ dataverse_gf_group }} state=present
  tags: dataverse

- name: create glassfish service account
  user: name={{ dataverse_gf_user }} group={{ dataverse_gf_group }}
  tags: dataverse

- name: glassfish service account should own {{ dataverse_gf_domain }}
  file: path={{ dataverse_gf_root }}/glassfish/domains/{{ dataverse_gf_domain }} owner={{ dataverse_gf_user }}
        group={{ dataverse_gf_group }} state=directory recurse=yes
  tags: dataverse

- name: remove old weld jar
  shell: /bin/rm {{ dataverse_gf_root }}/glassfish/modules/weld-osgi-bundle.jar
  tags: dataverse

- name: get patched weld jar
  get_url: url=http://central.maven.org/maven2/org/jboss/weld/weld-osgi-bundle/2.2.10.SP1/weld-osgi-bundle-2.2.10.SP1-glassfish4.jar 
        dest={{ dataverse_gf_root }}/glassfish/modules owner=root group=root mode=0644
  tags: dataverse

- name: remove old grizzly jar
  file: name={{ dataverse_gf_root }}/glassfish/modules/glassfish-grizzly-extra-all.jar state=absent
  tags: dataverse

- name: get patched grizzly jar
  get_url: url=http://guides.dataverse.org/en/latest/_static/installation/files/issues/2180/grizzly-patch/glassfish-grizzly-extra-all.jar
        dest={{ dataverse_gf_root }}/glassfish/modules owner=root group=root mode=0644
  tags: dataverse

- name: install glassfish systemd conf file for RedHat / CentOS7
  template: src=glassfish.service.j2 dest=/usr/lib/systemd/system/glassfish.service owner=root group=root mode=0644
  when: ansible_os_family == "RedHat" and
        ansible_distribution_major_version == "7"
  tags: dataverse

- name: reload systemd on RedHat/CentOS7
  shell: systemctl daemon-reload
  when: ansible_os_family == "RedHat" and
        ansible_distribution_major_version == "7"
  tags: dataverse

- name: enable glassfish on RedHat/CentOS7 - but don't start it with systemd during Ansible installation
  service: name=glassfish enabled=yes
  when: ansible_os_family == "RedHat" and
        ansible_distribution_major_version == "7"
  tags: dataverse

- name: install glassfish upstart script for Debian/Ubuntu
  template: src=glassfish.conf.j2 dest=/etc/init owner=root group=root mode=0644
  when: ansible_os_family == "Debian"
  tags: dataverse

- name: start glassfish with asadmin so subsequent IQSS-scripted restarts succeed on RedHat/CentOS
  become: yes
  become_user: "{{ dataverse_gf_user }}"
  shell: "nohup {{ dataverse_gf_root }}/bin/asadmin start-domain"
  when: ansible_os_family == "RedHat" and
        ansible_distribution_major_version == "7"
  tags: dataverse

- name: start glassfish on Debian/Ubuntu
  service: glassfish state=started
  when: ansible_os_family == "Debian"
  tags: dataverse

- name: download solr. unarchive urls supported in 2.0.
  get_url: url=https://archive.apache.org/dist/lucene/solr/4.6.0/solr-4.6.0.tgz dest=/tmp mode=0644
  tags: dataverse

- name: unpack solr
  shell: tar xvfz /tmp/solr-4.6.0.tgz -C /usr/local
  tags: dataverse

- name: move solr
  command: mv /usr/local/solr-4.6.0 /usr/local/solr
  tags: dataverse

- name: get updated solr schema
  get_url: url=https://github.com/IQSS/dataverse/releases/download/v4.2.1/schema.xml dest=/usr/local/solr/example/solr/collection1/conf/ owner={{ dataverse_gf_user }} group={{ dataverse_gf_group }} mode=0644
  tags: dataverse

- name: install solr upstart script for Debian/Ubuntu
  copy: src=solr.conf dest=/etc/init owner=root group=root mode=0644
  when: ansible_os_family == "Debian"
  tags: dataverse

- name: install solr systemd conf file for RedHat/CentOS
  copy: src=solr.service dest=/usr/lib/systemd/system owner=root group=root mode=0644
  when: ansible_os_family == "RedHat" and
        ansible_distribution_major_version == "7"
  tags: dataverse

- name: reload systemd
  shell: systemctl daemon-reload
  when: ansible_os_family == "RedHat" and
        ansible_distribution_major_version == "7"
  tags: dataverse

- name: enable solr on boot, start solr
  service: name=solr enabled=yes state=started
  when: ansible_os_family == "RedHat" and
        ansible_distribution_major_version == "7"
  tags: dataverse
