# THIS ANSIBLE PLAYBOOK FOR DEPLOYING AND INSTALLATION CAS AND LDAP
# current - Mike Conway
- hosts: cas
  sudo: yes
  sudo_user: root
  roles:
   - role: common
   - role: java7
   - role: ldap
   #- role: apache # install httpd
   #- role: tomcat # install tomcat and configure ajp
   #- role: cas
