# ansible-playbook -i inventories/... -K --tags "update_service_files" logstash-forwarder.yaml
# ansible-playbook -i inventories/... -K --tags "restart_services" logstash-forwarder.yaml


---
- name: Deploy Logstash Forwarder
  hosts: docker-ready
  sudo: yes
  roles:
    - role: notify-chat
      username: Logstash-Forwarder
      icon: ":memo:"
      msg: ":warning: Deploying Logstash Forwarder"

    - role: logstash-forwarder

    - role: notify-chat
      username: Logstash-Forwarder
      icon: ":memo:"
      msg: ":white_check_mark: Completed deploying Logstash Forwarder"
