---
- hosts: docker-ready
  roles:
    - role: docker
    - role: cron-stats
  environment:
    https_proxy: "{{ proxy_env.https_proxy }}"

- hosts: systems
  roles:
    - role: services-common
  environment:
      https_proxy: "{{ proxy_env.https_proxy }}"


