---
# kibana search tasks
#- name: search - all logged job submissions
#  uri: url="{{ s1_url }}" method=PUT
#      body={{ lookup('file', 's1-all-logged-job-submissions.json')|replace('\n', '')|to_nice_json }}
#  register: all_logged_job_submission
#  changed_when: all_logged_job_submission.status != 200 or
#               all_logged_job_submission.status != 201
#  failed_when: all_logged_job_submission.status != 200 and 
#               all_logged_job_submission.status != 201
#  tags:
#      - config
#      - config_kibana

- name: copy s1-all-logged-job-submissions.json to elk box
  copy: src=s1-all-logged-job-submissions.json dest=/tmp owner=root group=root mode=0644

- name: curl s1-all-logged-job-submissions.json because uri module barfs
  shell: "curl -v -XPUT {{ s1_url }} --data-binary @/tmp/s1-all-logged-job-submissions.json"
