- name: Add OS-specific varibles
  include_vars: "{{ ansible_os_family }}.yaml"
  tags: 
    - ldap
    - auth

- name: Install the openldap and required Packages for RedHat
  yum: name={{ item }} state=installed
  with_items: ldap_pkgs
  when: ansible_os_family == 'RedHat'
  tags: 
    - ldap
    - auth
