---

- name: stop firewalld, if running
  service: name=firewalld state=stopped
  ignore_errors: true

- name: mask firewalld service
  sudo: yes
  shell: systemctl mask firewalld

- name: install iptables-services
  yum: name=iptables-services state=latest

- name: insert iptables template
  template: src=iptables.j2 dest=/etc/sysconfig/iptables

- name: enable iptables at boot
  service: name=iptables state=started enabled=yes
