---
# tasks file for docker-cleanup

- name: Place the docker-gc-exclude (img exclusions) file
  template: src=docker-gc-exclude.j2 dest=/etc/docker-gc-exclude mode=0644
  when: config
  tags:
      - config

- name: Place the docker-gc-exclude-containers (container exclusions) file
  template: src=docker-gc-exclude-containers.j2 dest=/etc/docker-gc-exclude-containers mode=0644
  when: config
  tags:
      - config

- name: Place the 'docker-cleanup.service' file
  copy: src=docker-cleanup.service dest=/usr/lib/systemd/system/ group=root owner=root mode=0644
  when: config
  tags:
      - config

- name: Place the 'docker-cleanup.timer' file
  copy: src=docker-cleanup.timer dest=/usr/lib/systemd/system/ group=root owner=root mode=0644
  when: install_timer
  tags:
      - config

- name: Enable 'docker-cleanup.timer' file
  service: name=docker-cleanup.timer enabled=true state=started
  when: install_timer  
  tags:
      - config

- name: reload systemd
  shell: systemctl daemon-reload
  when: config
  tags:
      - config

- name: Initiate 'docker-cleanup' service
  service: name=docker-cleanup.service  state=started
  when: run_cleanup
