
#
# Properties file configuration
#
- name: ensure data directory exists
  file: path={{data_dir}}/cas/config state=directory owner={{tomcat_user}} group={{tomcat_user}}
  tags:
    - cas
    - properties

- name: copy all template configs
  template: src=config/cas.properties dest={{data_dir}}/cas/config/cas.properties
  tags:
    - cas
    - properties

- name: set data ownership [all data is owned by tomcat]
  file: path={{data_dir}}/cas owner={{tomcat_user}} group={{tomcat_user}} recurse=true  
  tags:
    - cas
    - properties

- name: ensure ssl certificate directory exists (if required)
  file: path={{ ssl_certificate_server_dir }} state=directory owner={{tomcat_user}} group={{tomcat_user}}
  when: do_ssl_config
  tags:
    - cas
    - properties
    - apache_vhost

- name: copy SSL files (if required)
  copy: src={{item}} dest={{ssl_certificate_server_dir}}
  when: do_ssl_config
  with_items:
    - "{{ssl_certificate_local_dir}}/{{ssl_cert_file}}"
    - "{{ssl_certificate_local_dir}}/{{ssl_key_file}}"
    - "{{ssl_certificate_local_dir}}/{{ssl_chain_file}}"
  tags:
    - cas
    - properties
    - apache_vhost

#
# WAR file deployment and virtual host configuration
#

- include: ../../apache_vhost/tasks/main.yml 
     context_path='{{ cas_context_path }}' 
     hostname='{{ cas_hostname }}' 
     ssl="true"
     ssl_cert_file='{{ssl_certificate_server_dir}}/{{ ssl_cert_file }}'
     ssl_key_file='{{ssl_certificate_server_dir}}/{{ ssl_key_file }}'
     ssl_chain_file='{{ssl_certificate_server_dir}}/{{ ssl_chain_file }}'
  tags:
    - cas
    - deploy
    - apache_vhost

- include: ../../tomcat_deploy/tasks/main.yml war_url='{{ cas_war_url }}' context_path='{{ cas_context_path }}' hostname='{{ cas_hostname }}'
  tags:
    - cas
    - deploy
    - tomcat_vhost

#
# Override the default memory settings for Tomcat to increase heap space and change the garbage collector
#
- name: Override default tomcat memory configuration
  lineinfile:
    dest={{tomcat_conf}}
    regexp="^JAVA_OPTS"
    line='JAVA_OPTS="{{tomcat_java_opts_override}}"'
  notify:
    - restart tomcat
  tags:
    - cas
    - deploy
    - tomcat
