---
- name: place iplant-data service files
  sudo: yes
  template: src=iplant-data.service dest=/usr/lib/systemd/system/ group=root owner=root mode=0664
  tags:
      - update_service_files

- name: reload systemd
  sudo: yes
  shell: systemctl daemon-reload  
  tags:
      - update_service_files
 
- name: start iplant-data container
  sudo: yes
  service: name={{data_container.service_name}} state=restarted
  tags:
      - restart_services
      - restart_iplant_data
