---
- name: remove old iplant_data container
  sudo: yes
  shell: "docker rm {{ data_container.container_name }}"
  ignore_errors: yes
  when: replace_container
  tags:
      - docker_rm_iplant_data

- name: login to data_container repository
  sudo: yes
  shell: "docker login -e {{ data_container.unc_registry_mail }} -p {{ data_container.unc_registry_pass }} -u {{ data_container.unc_registry_user }} {{ data_container.unc_remote_registry }}"
  tags:
      - docker_pull

- name: pull de-data container
  sudo: yes
  shell: "docker pull {{ data_container.unc_remote_registry }}/{{ data_container.image_name }}:latest"
  tags:
      - docker_pull

- include: CentOS-7.yaml
  when: ansible_distribution == "CentOS" and
        ansible_distribution_major_version == "7"

- include: Ubuntu14.yaml
  when: ansible_distribution == "Ubuntu" and
        ansible_distribution_major_version == "14"
