---
- name: place iplant-data service files
  sudo: yes
  template: src=iplant-data.conf dest=/etc/init/ group=root owner=root mode=0664
  tags:
      - update_service_files

- name: enable iplant-data service
  sudo: yes
  shell: system enable iplant-data
  tags:
      - update_service_files
 
- name: start iplant-data container
  sudo: yes
  service: name={{data_container.service_name}} state=restarted
  tags:
      - restart_services
      - restart_iplant_data
