# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.define "ubuntu1" do |ubuntu1|
    ubuntu1.vm.box = "ubuntu/trusty64"
    ubuntu1.vm.network "private_network", ip: "192.168.33.8"
    config.vbguest.auto_update = false
  end
  config.vm.define "ubuntu2" do |ubuntu2|
    ubuntu2.vm.box = "ubuntu/trusty64"
    ubuntu2.vm.network "private_network", ip: "192.168.33.9"
        config.vbguest.auto_update = false
  end
  config.vm.define "ubuntu3" do |ubuntu3|
    ubuntu3.vm.box ="ubuntu/trusty64"
    ubuntu3.vm.network "private_network", ip: "192.168.33.10"
        config.vbguest.auto_update = false
  end
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbook.yaml"
  end
end
