# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.define "ubuntu1" do |ubuntu1|
    ubuntu1.vm.box = "ubuntu/trusty64"
    ubuntu1.vm.network "private_network", ip: "192.168.33.8"
    config.vbguest.auto_update = false
  end

end
