# set up tomcat consistently whenever needed.  Used as:
# - include: ../common/tasks/tomcat.yml 
# "tomcat" variable controls version (@see common/vars)
- include: ../../common/tasks/setfacts.yml 

- name: install libtcnative
  yum: name=tomcat-native state=latest
  tags:
    - packages 
  when: ansible_os_family == "RedHat" and tomcat_apr == true
  tags:
    - tomcat

- name: install tomcat
  yum: name=tomcat state=present
  tags:
    - packages 
  notify: 
    - restart tomcat
  when: ansible_os_family == "RedHat"
  tags:
    - tomcat

- name: install libtcnative-1 (Debian)
  apt: pkg={{libtcnative}} state=present update_cache=yes
  tags:
    - packages 
  when: ansible_os_family == "Debian" and tomcat_apr == true
  tags:
    - tomcat

- name: install tomcat (Debian)
  apt: pkg={{tomcat}} state=present update_cache=yes
  tags:
    - packages 
  when: ansible_os_family == "Debian"
  register: tomcat_installed
  tags:
    - tomcat

- name: enable the AJP 1.3 connector
  tomcat_connector: name="AJP/1.3"
  tags: 
    - tomcat
  notify:
    - restart tomcat
