---
- name: install httplib2
  pip: name=httplib2
  tags:
      - config
      - config_elasticsearch

#- name: upload de-* index template
#  uri: url="{{es_de_index_template_url}}" method=PUT
#       body={{ lookup('file', 'de-template.json')|replace('\n', '')|to_nice_json }}
#  register: upload_de_index_template
#  tags:
#      - config
#      - config_elasticsearch

- name: copy de-template.json to elk box
  copy: src=de-template.json dest=/tmp owner=root group=root mode=0644
  tags:
      - config
      - config_elasticsearch

- name: curl de-template.json because uri module barfs
  shell: "curl -v -XPUT {{es_de_index_template_url}} --data-binary @/tmp/de-template.json"
  tags:
      - config
      - config_elasticsearch

#- name: upload de-metrics-* index template
#  uri: url="{{es_de_metrics_index_template_url}}" method=PUT
#       body={{ lookup('file', 'de-metrics-template.json')|replace('\n', '')|to_nice_json }}
#  register: upload_de_metrics_index_template
#  tags:
#      - config
#      - config_elasticsearch

- name: copy de-metrics-template.json to elk box
  copy: src=de-metrics-template.json dest=/tmp owner=root group=root mode=0644
  tags:
      - config
      - config_elasticsearch

- name: curl de-metrics-template.json because uri module barfs
  shell: "curl -v -XPUT {{es_de_metrics_index_template_url}} --data-binary @/tmp/de-metrics-template.json"
  tags:
      - config
      - config_elasticsearch

#- name: upload de-logs-* index template
#  uri: url="{{es_de_logs_index_template_url}}" method=PUT
#       body={{ lookup('file', 'de-logs-template.json')|replace('\n', '')|to_nice_json }}
#  register: upload_de_logs_index_template
#  tags:
#      - config
#      - config_elasticsearch

- name: copy de-logs-template.json to elk box
  copy: src=de-logs-template.json dest=/tmp owner=root group=root mode=0644
  tags:
      - config
      - config_elasticsearch

- name: curl de-logs-template.json because uri module barfs
  shell: "curl -v -XPUT {{es_de_logs_index_template_url}} --data-binary @/tmp/de-logs-template.json"
  tags:
      - config
      - config_elasticsearch

#- name: upload de-error-logs-* index template
#  uri: url="{{es_de_error_logs_index_template_url}}" method=PUT
#       body={{ lookup('file', 'de-error-template.json')|replace('\n', '')|to_nice_json }}
#  register: upload_de_logs_index_template
#  tags:
#      - config
#      - config_elasticsearch

- name: copy de-error-template.json to elk box
  copy: src=de-error-template.json dest=/tmp owner=root group=root mode=0644
  tags:
      - config
      - config_elasticsearch

- name: curl de-error-template.json because uri module barfs
  shell: "curl -v -XPUT {{es_de_error_logs_index_template_url}} --data-binary @/tmp/de-error-template.json"
  tags:
      - config
      - config_elasticsearch

