---

- name: install epel repository
  yum: name=epel-release state=latest
  when: ansible_distribution == "CentOS"

- name: install server prereqs
  yum: name={{ item }} state=latest
  with_items:
    - curl
    - python-pip
    - python-simplejson
    - python-httplib2
