---

- name: install epel repository
  yum: name=epel-release state=latest
  when: ansible_os_family == "RedHat"

- name: install server prereqs
  yum: name={{ item }} state=latest
  with_items:
    - curl
    - libselinux-python
    - python-pip
    - python-simplejson
    - python-httplib2
